version: '3'
services:
  atando:
    build: .
    links:
    - db
    container_name: atando-react
    ports:
    - 3000:3000
    volumes:
    - /home/david/atando-app:/app

  db:
    container_name: atando-mysql
    volumes:
    - /tmp/mysql:/var/lib/mysql
    image: mysql
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
